# Generated by Django 5.0.6 on 2024-12-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
                ('price', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
