# Generated by Django 5.0.6 on 2024-12-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newer', '0002_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='item_name',
        ),
    ]
