# Generated by Django 5.0.6 on 2025-01-20 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('newer', '0005_perishableinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='profile',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
